### ISSUE TITLE
Amazing!

### ISSUE THREAD

**Issue by flatsiedatsie** [ghys/habot#21]
Wow! You have created so many things that make me think 'why is this not default yet'.

It could be really interesting to integrate this with Snips voice control?

**Comment by ghys** [comment]
Hi, thank you very much 😎 

There's work in progress to build up a common tag library which would accomodate all voice control extensions, including Alexa, Google, Mycroft and so on... that's why this little project remains unofficial, for now!
About Snips, I experimented with it a year ago, their product esp. the offline recognition is becoming very good, and it could probably be done - either by bypassing their NLU altogether or by using it instead of OpenNLP (but you'll have to configure it in their web console), and only passing the intents and entities to the HABot API, which isn't supported now.
Also HABot's answers are a little too generic right now when simply asked for information, like "here's what I found" or "is this what you wanted?", it doesn't make sense without seeing the card it's showing you. And building natural answers is hard 😢.
